"""fix_refresh_token_model

Revision ID: 4f5f04892d45
Revises: 4c816b5f3538
Create Date: 2026-02-08 14:25:05.387659

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f5f04892d45"
down_revision: Union[str, Sequence[str], None] = "4c816b5f3538"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        "refresh_tokens_user_id_fkey", "refresh_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("refresh_tokens_user_id_fkey", "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", "users", ["user_id"], ["id"], onupdate="CASCADE"
    )
    # ### end Alembic commands ###
